src/Ls/MediaBundle/Entity/MediaFile.php
<?php

namespace Ls\MediaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * MediaFile
 * @ORM\Table(name="media_file")
 * @ORM\Entity
 */
class MediaFile {
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @var integer
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $file_name;
    
    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $created_at;
    
    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @var \DateTime
     */
    private $updated_at;
    
    protected $file;
    
    /**
     * @ORM\ManyToOne(targetEntity="Media", inversedBy="files")
     * @ORM\JoinColumn(name="media_id", referencedColumnName="id")
     */
    private $media;
    
    /**
     * Constructor
     */
    public function __construct() {
        $this->created_at = new \DateTime();
    }
    
    /**
     * Get id
     *
     * @return integer
     */
    public function getId() {
        return $this->id;
    }
    
    /**
     * Set file_name
     *
     * @param string $file_name
     * @return MediaFile
     */
    public function setFileName($file_name = null)
    {
        $this->file_name = $file_name;
    }
    
    /**
     * Get file_name
     *
     * @return string
     */
    public function getFileName()
    {
        return $this->file_name;
    }
    
    /**
     * Set created_at
     *
     * @param \DateTime $created_at
     * @return MediaFile
     */
    public function setCreatedAt($created_at) {
        $this->created_at = $created_at;
        
        return $this;
    }
    
    /**
     * Get created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt() {
        return $this->created_at;
    }
    
    public function getMedia() {
        return $this->media;
    }
    
    public function setMedia(Media $media) {
        $this->media = $media;
        
        return $this;
    }
    
    /**
     * Set updated_at
     *
     * @param \DateTime $updated_at
     * @return MediaFile
     */
    public function setUpdatedAt($updated_at) {
        $this->updated_at = $updated_at;
        
        return $this;
    }
    
    /**
     * Get updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt() {
        return $this->updated_at;
    }
    
    public function setFile(UploadedFile $file = null) {
        $this->file = $file;
    }
    
    public function getFile() {
        return $this->file;
    }
    
    public function deleteFile() {
        if (!empty($this->file_name)) {
            $filename = $this->getFileAbsolutePath();
            
            if (file_exists($filename)) {
                @unlink($filename);
            }
        }
    }
    
    public function getFileAbsolutePath() {
        return empty($this->file_name) ? null : $this->getUploadRootDir() . DIRECTORY_SEPARATOR . $this->file_name;
    }
    
    public function getFileWebPath() {
        return empty($this->file_name) ? null : '/' . $this->getUploadDir(true) . '/' . rawurlencode($this->file_name);
    }
    
    public function getUploadRootDir() {
        return __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'web' . DIRECTORY_SEPARATOR . $this->getUploadDir();
    }
    
    protected function getUploadDir() {
        return 'upload/media-files';
    }
    
    public function upload() {
        if (null === $this->file) {
            return;
        }
        
        $sFileName = $this->getFileName();
        
        $this->file->move($this->getUploadRootDir(), $sFileName);
        
        unset($this->file);
    }
    
    public function __toString() {
        return $this->getId();
    }
}

src/Ls/MediaBundle/Controller/FrontController.php
<?php

namespace Ls\MediaBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

/**
 * Media controller.
 *
 */
class FrontController extends Controller {

    public function loginAction(Request $request) {
        if ($request->query->has('_locale')) {
            return $this->redirect($this->generateUrl('ls_events_media_login'));
        }
        
        $em = $this->getDoctrine()->getManager();

        $form = $this->createFormBuilder([])
            ->add('password', PasswordType::class, ['label' => 'Podaj hasło'])
            ->add('submit', SubmitType::class, ['label' => 'Przejdź dalej'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $password = $em->getRepository('LsSettingBundle:Setting')->findOneBy(['label' => 'kmevents_media_password'])->getValue();
            
            if ($data['password'] != $password) {
                $this->get('session')->getFlashBag()->add('error', 'Password error');
                return $this->redirect($this->generateUrl('ls_events_media_login'));
            } else {
                $this->get('session')->set('loginMedia', md5(date("d.m.Y")));

                return $this->redirect($this->generateUrl('ls_events_media'));
            }
        }

        return $this->render('LsMediaBundle:Front:login.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Media entities list.
     *
     */
    public function indexAction(Request $request) {
        if ($request->query->has('_locale')) {
            return $this->redirect($this->generateUrl('ls_events_media'));
        }

        if ($this->get('session')->get('loginMedia') != md5(date("d.m.Y"))) {
            return $this->redirect($this->generateUrl('ls_events_media_login'));
        }
        
        $em = $this->getDoctrine()->getManager();
        
        $qb = $em->createQueryBuilder();
        $query = $qb->select('m')
            ->from('LsMediaBundle:Media', 'm')
            ->getQuery();
        
        $entities = $query->getResult();
        
        return $this->render('LsMediaBundle:Front:index.html.twig', array(
            'entities' => $entities
        ));
    }
    
    /**
     * Finds and displays a Media entity.
     *
     */
    public function showAction(Request $request, $slug) {
        if ($request->query->has('_locale')) {
            return $this->redirect($this->generateUrl('ls_events_media'));
        }

        if ($this->get('session')->get('loginMedia') != md5(date("d.m.Y"))) {
            return $this->redirect($this->generateUrl('ls_events_media_login'));
        }
        
        $em = $this->getDoctrine()->getManager();

        $entity = $em->createQueryBuilder()
            ->select('m')
            ->from('LsMediaBundle:Media', 'm')
            ->andWhere('m.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult();
        
        return $this->render('LsMediaBundle:Front:show.html.twig', array(
            'entity' => $entity
        ));
    }
}

src/Ls/MediaBundle/Resources/views/Front/index.html.twig
{% extends '::index.html.twig' %}

{% block title %}Media - {{ parent() }}{% endblock %}
{% block description %}Media - {{ cms_config.get('seo_description_kmevents', '') }}{% endblock %}
{% block keywords %}Media, {{ cms_config.get('seo_keywords_kmevents', '') }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/lscore/css/media.css') }}" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block content %}
    <div id="media-page" class="actorsBackground">
        <div class="toMainPageWrapper">
            <div class="kmevents-container">
                <div class="toMainPage">
                    <a href="{{ path('ls_core_homepage') }}">Powrót do strony głównej</a>
                </div>
            </div>
        </div>
        
        <div class="kmeventsMenu">
            <div class="kmevents-container">
                <a href="{{ path('ls_section_kmevents') }}">
                    <img src="{{ asset('bundles/lscore/images/kmevents_logo.png') }}" class="kmeventsLogo" alt="kmevents" />
                </a>
                <div class="kmeventsMenu_navWrapper">
                    {{ knp_menu_render(menuEvents) }}
                    <div class="socialsNetworks">
                        <a class="socialsNetworks_facebook" href="{{ cms_config.get('km_events_facebook', '')|nl2br|raw }}"></a>
                        <a class="socialsNetworks_instagram" href="{{ cms_config.get('km_events_instagram', '')|nl2br|raw }}"></a>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="actorContent">
            <div class="kmevents-container">
                <div class="media">
                    <h1 class="media-title">Media</h1>
                    
                    {% if entities|length > 0 %}
                        <div class="media-items">
                            {% for entity in entities %}
                                <a class="media-item" href="{{ path('ls_events_media_show', {'slug': entity.slug}) }}">
                                    <h1 class="media-item-title">{{ entity.title }}</h1>
                                </a>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Ls/MediaBundle/Resources/views/Front/login.html.twig
{% extends '::index.html.twig' %}

{% block title %}Media - {{ parent() }}{% endblock %}
{% block description %}Media - {{ cms_config.get('seo_description_kmevents', '') }}{% endblock %}
{% block keywords %}Media, {{ cms_config.get('seo_keywords_kmevents', '') }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/lscore/css/media.css') }}" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block content %}
    <div id="media-page" class="actorsBackground">
        <div class="toMainPageWrapper">
            <div class="kmevents-container">
                <div class="toMainPage">
                    <a href="{{ path('ls_core_homepage') }}">Powrót do strony głównej</a>
                </div>
            </div>
        </div>
        
        <div class="kmeventsMenu">
            <div class="kmevents-container">
                <a href="{{ path('ls_section_kmevents') }}">
                    <img src="{{ asset('bundles/lscore/images/kmevents_logo.png') }}" class="kmeventsLogo" alt="kmevents" />
                </a>
                <div class="kmeventsMenu_navWrapper">
                    {{ knp_menu_render(menuEvents) }}
                    <div class="socialsNetworks">
                        <a class="socialsNetworks_facebook" href="{{ cms_config.get('km_events_facebook', '')|nl2br|raw }}"></a>
                        <a class="socialsNetworks_instagram" href="{{ cms_config.get('km_events_instagram', '')|nl2br|raw }}"></a>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="actorContent">
            <div class="kmevents-container">
                <div class="media login-page">
                    {{ form_start(form, {'attr': {'id': form.vars.name, 'class': 'form-horizontal' }}) }}
                        <div class="form-group{% for flashMessage in app.session.flashbag.get('error') %} error{% endfor %}">
                            {{ form_label(form.password) }}
                            {{ form_widget(form.password, {'attr': {'class': 'form-control' }}) }}
                        </div>
                        <div class="form-buttons">
                            {{ form_widget(form.submit, {'attr': {'class': 'myButton myButton-green' }}) }}
                        </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/Ls/MediaBundle/Resources/views/Front/show.html.twig
{% extends '::index.html.twig' %}

{% block title %}Media - {{ entity.seotitle }} - {{ parent() }}{% endblock %}
{% block description %}{{ entity.seodescription }}{% endblock %}
{% block keywords %}{{ entity.seokeywords }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/lscore/css/media.css') }}" rel="stylesheet" type="text/css" media="all" />
{% endblock %}

{% block content %}
    <div id="media-page" class="actorsBackground">
        <div class="toMainPageWrapper">
            <div class="kmevents-container">
                <div class="toMainPage">
                    <a href="{{ path('ls_core_homepage') }}">Powrót do strony głównej</a>
                </div>
            </div>
        </div>
        
        <div class="kmeventsMenu">
            <div class="kmevents-container">
                <a href="{{ path('ls_section_kmevents') }}">
                    <img src="{{ asset('bundles/lscore/images/kmevents_logo.png') }}" class="kmeventsLogo" alt="kmevents" />
                </a>
                <div class="kmeventsMenu_navWrapper">
                    {{ knp_menu_render(menuEvents) }}
                    <div class="socialsNetworks">
                        <a class="socialsNetworks_facebook" href="{{ cms_config.get('km_events_facebook', '')|nl2br|raw }}"></a>
                        <a class="socialsNetworks_instagram" href="{{ cms_config.get('km_events_instagram', '')|nl2br|raw }}"></a>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="actorContent">
            <div class="kmevents-container">
                <div class="media">
                    <h1 class="media-title">Media</h1>
                    
                    <div class="media-show">
                        <div class="media-left">
                            <h2 class="media-show-title">{{ entity.title }}</h2>
                            
                            {% if entity.files|length > 0 %}
                                <div class="download">
                                    <h4 class="download-title">Zdjęcia do pobrania</h4>
                                    
                                    {% for file in entity.files %}
                                        <a class="download-link" href="{{ file.getFileWebPath }}" target="_blank">{{ file.fileName }}</a>
                                    {% endfor %}
                                </div>
                            {% endif %}
                            
                            {% if entity.links|length > 0 %}
                                <div class="media-links">
                                    <h4 class="media-links-title">Teledyski</h4>
                                    
                                    {% for link in entity.links %}
                                        <a class="media-link" href="{{ link.url }}" target="_blank">{{ link.title }}</a>
                                    {% endfor %}
                                </div>
                            {% endif %}
                            
                            {% if entity.facebook|length > 0 or entity.instagram|length > 0 or entity.youtube|length > 0 or entity.twitter|length > 0 %}
                                <div class="social-media">
                                    <h4 class="social-media-title">Social media:</h4>
                                    
                                    {% if entity.facebook|length > 0 %}
                                        <a class="social-media-link" href="{{ entity.facebook }}" target="_blank">Facebook</a>
                                    {% endif %}
                                    
                                    {% if entity.instagram|length > 0 %}
                                        <a class="social-media-link" href="{{ entity.instagram }}" target="_blank">Instagram</a>
                                    {% endif %}
                                    
                                    {% if entity.youtube|length > 0 %}
                                        <a class="social-media-link" href="{{ entity.youtube }}" target="_blank">YouTube</a>
                                    {% endif %}
                                    
                                    {% if entity.twitter|length > 0 %}
                                        <a class="social-media-link" href="{{ entity.twitter }}" target="_blank">Twitter</a>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="media-right editor">
                            <p class="media-page-title">Info prasowe</p>
                            {{ entity.content|raw }}
                            <p class="media-page-title">Bio Monika</p>
                            {{ entity.content2|raw }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    
    <script>
        // Menu item MEDIA add class "current"
        $('a[title="MEDIA"]').parent().addClass('current');
    </script>
{% endblock %}